### ISSUE TITLE
Broken archive verification

### ISSUE THREAD

**Issue by matejmode** [Fantom-foundation/Carmen#963] opened 2024-07-17 11:50 UTC
With @thaarok we have investigated the release testing failure. The fault is not related to the archive state, but, as reverting of the version proved, to the archive verification tool.

Archive verification succeeds for verification tool 46353a6b7b9ab551a557f897e1175b755c5d70cc
Archive verification fails with following error at 54a30889e0311491d62d88d08a965e91f91be69d
Seems 54a30889e0311491d62d88d08a965e91f91be69d introduce the verification tool bug.
```
go run ./database/mpt/tool/ verify /var/data/testing-archive-verify/tmp/state_db_carmen_go-file_800000_broken_on_last/archive/
11:40:31 [t=   0:00] - Starting verification ...
11:40:31 [t=   0:00] - Obtaining read access to files ...
11:40:31 [t=   0:00] - Checking contract codes ...
11:40:31 [t=   0:00] - Checking forest stored in /var/data/testing-archive-verify/tmp/state_db_carmen_go-file_800000_broken_on_last/archive/ ...
11:40:31 [t=   0:00] - Checking meta-data ...
11:40:31 [t=   0:00] - Checking node references ...
11:40:40 [t=   0:09] - Checking 800000 root hashes ...
11:40:42 [t=   0:11] - Getting refeences to children for accounts (batch 1, size: 720828039)...
11:40:43 [t=   0:12] - Loading 251410 child hashes for accounts (batch 1, size: 720828039)...
11:40:46 [t=   0:15] - Checking hashes of up to 707769 accounts (batch 1, size: 720828039)...
11:40:49 [t=   0:18] - Getting refeences to children for branchs (batch 1, size: 720828039)...
11:41:05 [t=   0:33] - Loading 6456725 child hashes for branchs (batch 1, size: 720828039)...
11:41:41 [t=   1:09] - Checking hashes of up to 5288000 branchs (batch 1, size: 720828039)...
11:42:13 [t=   1:42] - Getting refeences to children for extensions (batch 1, size: 720828039)...
11:42:13 [t=   1:42] - Loading 21486 child hashes for extensions (batch 1, size: 720828039)...
11:42:13 [t=   1:42] - Checking hashes of up to 22137 extensions (batch 1, size: 720828039)...
11:42:15 [t=   1:44] - Getting refeences to children for values (batch 1, size: 720828039)...
11:42:16 [t=   1:45] - Loading 0 child hashes for values (batch 1, size: 720828039)...
11:42:16 [t=   1:45] - Checking hashes of up to 1015628 values (batch 1, size: 720828039)...
invalid hash stored for node 687380, want [222 156 61 29 146 91 161 79 176 67 55 117 253 105 159 79 127 40 121 35 14 124 165 223 108 166 127 26 70 23 31 0], got [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
exit status 1

```

**Comment by HerbertJordan** [comment] 2024-07-17 12:26
The issue can already be reproduced with an archive that only covers the first 1M blocks.

**Comment by HerbertJordan** [comment] 2024-07-17 12:35
It might be an issue in the verification tool. I checked the 1M archive created with an up-to-date Carmen using older versions of the verification tool.

When using the command
```
go run ./database/mpt/tool verify /tmp/state_db_carmen_go-file_1000000/archive
```
the verification passes for bbcfc5b75e54eee05f2106e5401a2e59e90860b9 but fails for 8657434bf31efe182a387b3b2416f0d9eada9a63.

One could bisect between those commits to try to identify the breaking change.

**Comment by thaarok** [comment] 2024-07-17 13:34
@HerbertJordan we have already done the bisect - the breaking change is 54a30889e0311491d62d88d08a965e91f91be69d

**Comment by kjezek** [comment] 2024-07-17 15:27
From this commit, only the follwing change could have relevance to the verification tool:
[https://github.com/Fantom-foundation/Carmen/commit/54a30889e0311491d62d88d08a965e91f91be69d#diff-08173b99556edc52648c2[…]cfea0eeecf44e35c43R463-R465](https://github.com/Fantom-foundation/Carmen/commit/54a30889e0311491d62d88d08a965e91f91be69d#diff-08173b99556edc52648c24b96e27ddcf4fa9c222b00580cfea0eeecf44e35c43R463-R465)

the other modifications are very likely unrelated

**Comment by kjezek** [comment] 2024-07-17 18:59
The issue is clear I think. The code was updated that when hashing an embedded node, its content is returned instead. Now when verification is happening, it is checked if hashing the node provides the same hash as the hash stored for this node. For embedded nodes, the hash is zero, which suddenly does not match with what we return. 

A possible solution is skip verification of embedded nodes.

**Comment by kjezek** [comment] 2024-07-18 06:18
should be fixed when https://github.com/Fantom-foundation/Carmen/pull/965 merged

**Closed** 2024-07-18 20:50 UTC
Labels: bug
