### ISSUE TITLE
Dead-Lock between Visitor and Node flusher

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#1028] opened 2024-09-18 06:59 UTC
While testing the parallel export code a deadlock between a node visitor and the node flusher was detected:
```
running tests:
	TestVisit_CanHandleSlowConsumer (1m49s)

goroutine 499 [sync.Mutex.Lock, 1 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/home/herbert/sdk/go1.21.0/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc0004bc028)
	/home/herbert/sdk/go1.21.0/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/home/herbert/sdk/go1.21.0/src/sync/mutex.go:90
github.com/Fantom-foundation/Carmen/go/database/mpt.(*writeBuffer).Cancel(0xc0004bc000, 0xc0015b39c0?)
	/home/herbert/coding/fantom/carmen/go/database/mpt/write_buffer.go:146 +0x5f
github.com/Fantom-foundation/Carmen/go/database/mpt.(*Forest).addToCacheHoldingTransferMutex(0xc0000c2000, 0xc001867bf0, 0xc0015b39c0)
	/home/herbert/coding/fantom/carmen/go/database/mpt/forest.go:883 +0x3e
github.com/Fantom-foundation/Carmen/go/database/mpt.(*Forest).getSharedNode(0xc0000c2000, 0xc001867bf0)
	/home/herbert/coding/fantom/carmen/go/database/mpt/forest.go:749 +0x605
github.com/Fantom-foundation/Carmen/go/database/mpt.getAccess[...](0xc00032d520?, 0x410ae5?, 0x658e88?, 0x658e90, {{0x1}})
	/home/herbert/coding/fantom/carmen/go/database/mpt/forest.go:760 +0x36
github.com/Fantom-foundation/Carmen/go/database/mpt.(*Forest).getViewAccess(0xc0018cd800?, 0x696ea0?)
	/home/herbert/coding/fantom/carmen/go/database/mpt/forest.go:795 +0x31
github.com/Fantom-foundation/Carmen/go/database/mpt.(*BranchNode).Visit(0xc0000dc400, {0x696ea0, 0xc0000c2000}, 0xc0017af5a8, 0x3, {0x694d40, 0xc00210e000})
	/home/herbert/coding/fantom/carmen/go/database/mpt/nodes.go:1042 +0x1ec
github.com/Fantom-foundation/Carmen/go/database/mpt.(*BranchNode).Visit(0xc000003c00, {0x696ea0, 0xc0000c2000}, 0xc00181f920, 0x2, {0x694d40, 0xc00210e000})
	/home/herbert/coding/fantom/carmen/go/database/mpt/nodes.go:1044 +0x2d0
github.com/Fantom-foundation/Carmen/go/database/mpt.(*BranchNode).Visit(0xc000110800, {0x696ea0, 0xc0000c2000}, 0xc000028140, 0x1, {0x694d40, 0xc00210e000})
	/home/herbert/coding/fantom/carmen/go/database/mpt/nodes.go:1044 +0x2d0
github.com/Fantom-foundation/Carmen/go/database/mpt.(*AccountNode).visitStorage(0xc001836050?, {0x696ea0, 0xc0000c2000}, 0x575391?, {0x694d40, 0xc00210e000})
	/home/herbert/coding/fantom/carmen/go/database/mpt/nodes.go:1936 +0x152
github.com/Fantom-foundation/Carmen/go/database/mpt.(*AccountNode).Visit(0x78d08e888dd0?, {0x696ea0, 0xc0000c2000}, 0xc001836050, 0x0, {0x694d40?, 0xc00210e000?})
	/home/herbert/coding/fantom/carmen/go/database/mpt/nodes.go:1926 +0xcf
github.com/Fantom-foundation/Carmen/go/database/mpt.(*Forest).VisitTrie(0xc0000c2000, 0xc001836050, {0x694d40, 0xc00210e000})
	/home/herbert/coding/fantom/carmen/go/database/mpt/forest.go:456 +0x25b
github.com/Fantom-foundation/Carmen/go/database/mpt.(*LiveTrie).VisitTrie(...)
	/home/herbert/coding/fantom/carmen/go/database/mpt/live_trie.go:172
github.com/Fantom-foundation/Carmen/go/database/mpt.(*MptState).Visit(...)
	/home/herbert/coding/fantom/carmen/go/database/mpt/state.go:350
github.com/Fantom-foundation/Carmen/go/database/mpt/io.TestVisit_CanHandleSlowConsumer(0xc001935040)
	/home/herbert/coding/fantom/carmen/go/database/mpt/io/parallel_visit_test.go:192 +0x4f8
testing.tRunner(0xc001935040, 0x6586c0)
	/home/herbert/sdk/go1.21.0/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/home/herbert/sdk/go1.21.0/src/testing/testing.go:1648 +0x3ad

goroutine 429 [sync.RWMutex.Lock, 1 minutes, locked to thread]:
sync.runtime_SemacquireRWMutex(0x0?, 0x24?, 0x4b4960?)
	/home/herbert/sdk/go1.21.0/src/runtime/sema.go:87 +0x25
sync.(*RWMutex).Lock(0x6058a0?)
	/home/herbert/sdk/go1.21.0/src/sync/rwmutex.go:152 +0x6a
github.com/Fantom-foundation/Carmen/go/database/mpt/shared.(*Shared[...]).GetWriteHandle(...)
	/home/herbert/coding/fantom/carmen/go/database/mpt/shared/shared.go:168
github.com/Fantom-foundation/Carmen/go/database/mpt.(*writeBuffer).emptyBuffer(0xc0004bc000)
	/home/herbert/coding/fantom/carmen/go/database/mpt/write_buffer.go:206 +0x2de
github.com/Fantom-foundation/Carmen/go/database/mpt.makeWriteBuffer.func1()
	/home/herbert/coding/fantom/carmen/go/database/mpt/write_buffer.go:104 +0xe5
created by github.com/Fantom-foundation/Carmen/go/database/mpt.makeWriteBuffer in goroutine 499
	/home/herbert/coding/fantom/carmen/go/database/mpt/write_buffer.go:98 +0x1ab

goroutine 428 [chan receive, 1 minutes]:
github.com/Fantom-foundation/Carmen/go/database/mpt.makeForest.func1()
	/home/herbert/coding/fantom/carmen/go/database/mpt/forest.go:322 +0x109
created by github.com/Fantom-foundation/Carmen/go/database/mpt.makeForest in goroutine 499
	/home/herbert/coding/fantom/carmen/go/database/mpt/forest.go:318 +0x930

goroutine 427 [select]:
github.com/Fantom-foundation/Carmen/go/database/mpt.startNodeFlusher.func1()
	/home/herbert/coding/fantom/carmen/go/database/mpt/node_flusher.go:52 +0x132
created by github.com/Fantom-foundation/Carmen/go/database/mpt.startNodeFlusher in goroutine 499
	/home/herbert/coding/fantom/carmen/go/database/mpt/node_flusher.go:47 +0x192
FAIL	github.com/Fantom-foundation/Carmen/go/database/mpt/io	120.011s
FAIL
```

The working-hypothesis for the cause of the issue is as follows:
- (A) the visitor is retaining view permissions for all the nodes along the path
- (B) the visitor tries to revive a node from the node flusher
- (C) the node flusher is currently attempting to flush a node along the visitor path

C blocks B by holding the write-buffer lock (attempted to be acquired by B [here](https://github.com/Fantom-foundation/Carmen/blob/8b4fd1bf05a531830ac6158d4558eb59ea810f8c/go/database/mpt/write_buffer.go#L146), owned by C [here](https://github.com/Fantom-foundation/Carmen/blob/8b4fd1bf05a531830ac6158d4558eb59ea810f8c/go/database/mpt/write_buffer.go#L198)).

B blocks A because these are nested steps in the visiting process.

A blocks C because one of the nodes in the path is the one C tries to gain write access on.

**Comment by kjezek** [comment] 2024-09-26 06:51
Many experiments to verify witness proof ended up being stuck. I guess it can be also caused by this deadlock. 

Triggered by command: 
```
go run ./tool/ verify-proof --block-num 80000000 /mnt/disks/ssd-array/carmen/archive
```

**Comment by kjezek** [comment] 2024-09-27 07:19
> Many experiments to verify witness proof ended up being stuck. I guess it can be also caused by this deadlock.
> 
> Triggered by command:
> 
> ```
> go run ./tool/ verify-proof --block-num 80000000 /mnt/disks/ssd-array/carmen/archive
> ```

It turns out it did not stop, it was processing 7hours one segment, i.e. a big account
```
13:17:14 [t=1527:02] -   ... verified 131000000 addresses
13:27:19 [t=1537:07] -   ... verified 132000000 addresses
( 7 hours gap !!)
20:50:23 [t=3420:11] -   ... verified 133000000 addresses
20:58:54 [t=3428:42] -   ... verified 134000000 addresses
21:08:14 [t=3438:02] -   ... verified 135000000 addresses
…. (shortened)
01:48:47 [t=3718:35] -   ... verified 167000000 addresses
01:56:40 [t=3726:28] -   ... verified 168000000 addresses
02:01:12 [t=3731:00] - Veryfing 1000 empty addresses...
02:01:35 [t=3731:23] - Verification successful!
```

**Comment by kjezek** [comment] 2024-10-23 13:20
fixed by https://github.com/Fantom-foundation/Carmen/pull/1048

**Closed by kjezek** 2024-10-23 13:20 UTC
Labels: bug
