### ISSUE TITLE
Support exporting of LiveDB genesis data from Archive

### ISSUE THREAD

**Issue by kjezek** [Fantom-foundation/Carmen#877] opened 2024-05-23 09:30 UTC
Right now, to produce a genesis file for a given block height, a node has to be synced up to the desired height and stopped to be able to export the LiveDB state from an offline DB.

However, LiveDB data could also be exported from Archives while being live, without the need to take the Archive offline. This feature should be implemented.

**Comment by HerbertJordan** [comment] 2024-06-24 16:49
This is a duplicate of #680

**Closed by HerbertJordan** 2024-06-24 16:49 UTC
